import { MissionConfig, OperativeClass, OperativeInfo, Weapon } from '../types/game';

export const OPERATIVES: Record<OperativeClass, OperativeInfo> = {
  ghost: {
    id: 'ghost',
    name: 'GHOST',
    codename: 'Agente 01 - Fantasma',
    role: 'Especialista en Infiltración',
    avatarColor: '#10b981', // Emerald
    speed: 4.8,
    maxHp: 100,
    armor: 40,
    gadget: 'smoke_grenade',
    primaryWeapon: {
      name: 'Silenced 9mm Whisper',
      type: 'pistol_silenced',
      damage: 38,
      fireRate: 4.5,
      range: 360,
      magSize: 15,
      reloadTime: 1.2,
      isSilenced: true,
      spread: 0.04,
      bulletSpeed: 18,
      color: '#34d399',
    },
    description: 'Movimiento veloz e indetectable. Elimina objetivos silenciosamente sin activar alarmas.',
    specialAbility: 'Granada de Humo: Bloquea la visión de cámaras y guardias durante 8 segundos.',
  },
  viper: {
    id: 'viper',
    name: 'VIPER',
    codename: 'Agente 02 - Víbora',
    role: 'Hacker de Operaciones Negras',
    avatarColor: '#06b6d4', // Cyan
    speed: 4.5,
    maxHp: 90,
    armor: 50,
    gadget: 'emp_charge',
    primaryWeapon: {
      name: 'Silenced MPX-T Tactical',
      type: 'smg_silenced',
      damage: 26,
      fireRate: 8.5,
      range: 320,
      magSize: 28,
      reloadTime: 1.5,
      isSilenced: true,
      spread: 0.07,
      bulletSpeed: 19,
      color: '#38bdf8',
    },
    description: 'Experta en contramedidas electrónicas. Desactiva terminales y cámaras a doble velocidad.',
    specialAbility: 'Pulso EMP: Desactiva temporalmente cámaras, torretas y redes láser en un área amplia.',
  },
  titan: {
    id: 'titan',
    name: 'TITAN',
    codename: 'Agente 03 - Titán',
    role: 'Especialista en Demolición y Fuego',
    avatarColor: '#f59e0b', // Amber
    speed: 4.0,
    maxHp: 150,
    armor: 120,
    gadget: 'breach_c4',
    primaryWeapon: {
      name: 'Tactical Assault Rifle MK17',
      type: 'assault_rifle',
      damage: 48,
      fireRate: 6.0,
      range: 420,
      magSize: 30,
      reloadTime: 1.8,
      isSilenced: false,
      spread: 0.08,
      bulletSpeed: 22,
      color: '#fbbf24',
    },
    description: 'Blindaje pesado y máxima potencia de fuego. Capaz de contener oleadas completas de SWAT.',
    specialAbility: 'Carga C4: Detona barricadas y elimina grupos de enemigos fuertemente blindados.',
  },
  spectre: {
    id: 'spectre',
    name: 'SPECTRE',
    codename: 'Agente 04 - Espectro',
    role: 'Tirador y Reconocimiento',
    avatarColor: '#a855f7', // Purple
    speed: 4.3,
    maxHp: 95,
    armor: 45,
    gadget: 'recon_dart',
    primaryWeapon: {
      name: 'Silenced DMR Shadow-7',
      type: 'sniper_suppressed',
      damage: 90,
      fireRate: 1.8,
      range: 580,
      magSize: 10,
      reloadTime: 2.0,
      isSilenced: true,
      spread: 0.015,
      bulletSpeed: 26,
      color: '#c084fc',
    },
    description: 'Precisión letal a larga distancia. Perfora blindajes de un solo disparo a la cabeza.',
    specialAbility: 'Dardo de Reconocimiento: Revela la posición de todos los enemigos y cámaras a través de muros.',
  },
};

export const ENEMY_WEAPONS: Record<string, Weapon> = {
  guard_pistol: {
    name: 'Service Pistol',
    type: 'pistol_silenced',
    damage: 14,
    fireRate: 2.0,
    range: 300,
    magSize: 12,
    reloadTime: 2.0,
    isSilenced: false,
    spread: 0.12,
    bulletSpeed: 14,
    color: '#ef4444',
  },
  swat_smg: {
    name: 'SWAT SMG',
    type: 'smg_silenced',
    damage: 18,
    fireRate: 5.5,
    range: 350,
    magSize: 30,
    reloadTime: 2.2,
    isSilenced: false,
    spread: 0.1,
    bulletSpeed: 16,
    color: '#f87171',
  },
  turret_cannon: {
    name: 'Automated Gatling',
    type: 'assault_rifle',
    damage: 16,
    fireRate: 7.0,
    range: 400,
    magSize: 999,
    reloadTime: 0.1,
    isSilenced: false,
    spread: 0.14,
    bulletSpeed: 17,
    color: '#ff2020',
  }
};

export const MISSIONS: MissionConfig[] = [
  {
    id: 'mission_1',
    name: 'Operación Blackout (Data Vault)',
    code: 'OP-BLACKOUT',
    location: 'Centro de Datos Subterráneo Nexus-9',
    difficulty: 'EASY',
    description: 'Infiltra el centro de servidores, desactiva la red láser sincronizando dos terminales, extrae el Núcleo Cuántico y escapa.',
    briefing: [
      '1. Elimina o esquiva a los 2 guardias del vestíbulo inicial en sigilo.',
      '2. Coordinad a ambos operativos para activar simultáneamente las terminales Alpha y Beta (ventana de 3 segundos).',
      '3. Desactiva la cuadrícula láser, roba el Núcleo de Datos y el dinero de las cajas fuertes.',
      '4. Llega a la zona de extracción en el Metro antes de que la alarma general bloquee el complejo.'
    ],
    targetLootValue: 250000,
    timeLimitSeconds: 120,
    qrfSpawnInterval: 14,
    mapWidth: 1600,
    mapHeight: 1000,
    spawnP1: { x: 120, y: 500 },
    spawnP2: { x: 120, y: 560 },
    walls: [
      // Outer boundaries
      { x: 0, y: 0, width: 1600, height: 20 },
      { x: 0, y: 980, width: 1600, height: 20 },
      { x: 0, y: 0, width: 20, height: 1000 },
      { x: 1580, y: 0, width: 20, height: 1000 },

      // Entry Room walls
      { x: 260, y: 20, width: 20, height: 380 },
      { x: 260, y: 600, width: 20, height: 380 },

      // Central Corridor Dividing Walls
      { x: 480, y: 200, width: 340, height: 20 },
      { x: 480, y: 780, width: 340, height: 20 },

      // Top Security Terminal Room
      { x: 480, y: 20, width: 20, height: 180 },
      { x: 820, y: 20, width: 20, height: 180 },

      // Bottom Security Terminal Room
      { x: 480, y: 800, width: 20, height: 180 },
      { x: 820, y: 800, width: 20, height: 180 },

      // Middle Vault Blast Walls
      { x: 920, y: 160, width: 20, height: 280 },
      { x: 920, y: 560, width: 20, height: 280 },
      { x: 920, y: 160, width: 360, height: 20 },
      { x: 920, y: 820, width: 360, height: 20 },
      { x: 1260, y: 160, width: 20, height: 680 },

      // Pillars / Cover boxes
      { x: 380, y: 440, width: 40, height: 40, isCover: true },
      { x: 380, y: 580, width: 40, height: 40, isCover: true },
      { x: 650, y: 460, width: 60, height: 80, isCover: true },
      { x: 1060, y: 380, width: 60, height: 40, isCover: true },
      { x: 1060, y: 580, width: 60, height: 40, isCover: true },
    ],
    doors: [
      { id: 'door_entry', x: 260, y: 400, width: 20, height: 200, isOpen: true, isLocked: false, isVertical: true },
      { id: 'door_vault', x: 920, y: 440, width: 20, height: 120, isOpen: false, isLocked: true, lockedReason: 'BARRERA LÁSER ACTIVA', isVertical: true, unlockedByTerminalGroup: 'group_term_1' },
      { id: 'door_extract', x: 1260, y: 440, width: 20, height: 120, isOpen: true, isLocked: false, isVertical: true }
    ],
    terminals: [
      {
        id: 'term_1a',
        pairedTerminalId: 'term_1b',
        group: 'group_term_1',
        x: 650,
        y: 100,
        radius: 40,
        isActivated: false,
        activeByPlayer: null,
        activatedTime: 0,
        syncWindowSeconds: 3.5,
        requiresKeycard: false,
        label: 'TERMINAL ALPHA (PISO NORTE)',
        isCompleted: false,
        unlocksDoorId: 'door_vault',
        progress: 0,
      },
      {
        id: 'term_1b',
        pairedTerminalId: 'term_1a',
        group: 'group_term_1',
        x: 650,
        y: 900,
        radius: 40,
        isActivated: false,
        activeByPlayer: null,
        activatedTime: 0,
        syncWindowSeconds: 3.5,
        requiresKeycard: false,
        label: 'TERMINAL BETA (PISO SUR)',
        isCompleted: false,
        unlocksDoorId: 'door_vault',
        progress: 0,
      }
    ],
    lasers: [
      { id: 'laser_1', x1: 930, y1: 450, x2: 930, y2: 550, isActive: true, controlledByTerminalGroup: 'group_term_1', color: '#ef4444' },
      { id: 'laser_2', x1: 930, y1: 475, x2: 930, y2: 525, isActive: true, controlledByTerminalGroup: 'group_term_1', color: '#ef4444' },
    ],
    cameras: [
      {
        id: 'cam_1',
        x: 480,
        y: 230,
        angle: Math.PI / 4,
        baseAngle: Math.PI / 4,
        sweepAngle: Math.PI / 2.5,
        sweepSpeed: 0.8,
        viewDistance: 220,
        viewFov: 0.6,
        isHacked: false,
        hackTimer: 0,
        detectionLevel: 0,
        detectionTarget: null,
      },
      {
        id: 'cam_2',
        x: 480,
        y: 770,
        angle: -Math.PI / 4,
        baseAngle: -Math.PI / 4,
        sweepAngle: Math.PI / 2.5,
        sweepSpeed: 0.8,
        viewDistance: 220,
        viewFov: 0.6,
        isHacked: false,
        hackTimer: 0,
        detectionLevel: 0,
        detectionTarget: null,
      }
    ],
    enemies: [
      // Patrol 1 - Lobby Guard (Immediate stealth challenge in first 10 seconds)
      {
        id: 'enemy_1',
        type: 'guard_patrol',
        x: 390,
        y: 350,
        vx: 0,
        vy: 0,
        angle: Math.PI / 2,
        hp: 60,
        maxHp: 60,
        state: 'patrol',
        stateTimer: 0,
        speed: 1.6,
        viewDistance: 240,
        viewAngle: Math.PI / 3.2,
        patrolPoints: [{ x: 390, y: 350 }, { x: 390, y: 650 }],
        currentPatrolIdx: 0,
        investigatePos: null,
        targetPlayerId: null,
        lastShotTime: 0,
        detectionLevel: 0,
        isStunned: false,
        stunTimer: 0,
        color: '#ef4444',
        weapon: ENEMY_WEAPONS.guard_pistol,
      },
      // Patrol 2 - North corridor
      {
        id: 'enemy_2',
        type: 'guard_patrol',
        x: 650,
        y: 320,
        vx: 0,
        vy: 0,
        angle: 0,
        hp: 60,
        maxHp: 60,
        state: 'patrol',
        stateTimer: 0,
        speed: 1.5,
        viewDistance: 240,
        viewAngle: Math.PI / 3.2,
        patrolPoints: [{ x: 520, y: 320 }, { x: 780, y: 320 }],
        currentPatrolIdx: 0,
        investigatePos: null,
        targetPlayerId: null,
        lastShotTime: 0,
        detectionLevel: 0,
        isStunned: false,
        stunTimer: 0,
        color: '#ef4444',
        weapon: ENEMY_WEAPONS.guard_pistol,
      },
      // Patrol 3 - South corridor
      {
        id: 'enemy_3',
        type: 'guard_patrol',
        x: 650,
        y: 680,
        vx: 0,
        vy: 0,
        angle: Math.PI,
        hp: 60,
        maxHp: 60,
        state: 'patrol',
        stateTimer: 0,
        speed: 1.5,
        viewDistance: 240,
        viewAngle: Math.PI / 3.2,
        patrolPoints: [{ x: 780, y: 680 }, { x: 520, y: 680 }],
        currentPatrolIdx: 0,
        investigatePos: null,
        targetPlayerId: null,
        lastShotTime: 0,
        detectionLevel: 0,
        isStunned: false,
        stunTimer: 0,
        color: '#ef4444',
        weapon: ENEMY_WEAPONS.guard_pistol,
      },
      // Vault Guard - Elite
      {
        id: 'enemy_4',
        type: 'guard_elite',
        x: 1080,
        y: 500,
        vx: 0,
        vy: 0,
        angle: Math.PI,
        hp: 110,
        maxHp: 110,
        state: 'patrol',
        stateTimer: 0,
        speed: 1.8,
        viewDistance: 260,
        viewAngle: Math.PI / 3,
        patrolPoints: [{ x: 1080, y: 400 }, { x: 1080, y: 600 }],
        currentPatrolIdx: 0,
        investigatePos: null,
        targetPlayerId: null,
        lastShotTime: 0,
        detectionLevel: 0,
        isStunned: false,
        stunTimer: 0,
        color: '#f97316',
        weapon: ENEMY_WEAPONS.swat_smg,
      }
    ],
    loot: [
      { id: 'loot_core', type: 'crypto_core', name: 'NÚCLEO CUÁNTICO NEXUS', value: 150000, x: 1150, y: 500, weight: 0.15, isCollected: false, isPrimaryObjective: true },
      { id: 'loot_cash1', type: 'cash', name: 'Fajos de Billetes No Trazables', value: 40000, x: 1000, y: 300, weight: 0.05, isCollected: false },
      { id: 'loot_cash2', type: 'cash', name: 'Fajos de Billetes No Trazables', value: 40000, x: 1000, y: 700, weight: 0.05, isCollected: false },
      { id: 'loot_intel', type: 'classified_intel', name: 'Disco de Claves Cifradas', value: 20000, x: 720, y: 100, weight: 0.02, isCollected: false }
    ],
    extractionZone: {
      x: 1400,
      y: 400,
      width: 140,
      height: 200,
      isActive: true,
      evacProgress: 0,
      evacRequiredSeconds: 3.5,
      name: 'METRO SUBTERRÁNEO LÍNEA-7'
    },
    objectives: [
      { id: 'obj_sync', text: 'Sincronizar Terminales Alpha y Beta para desactivar el láser', isCompleted: false, isOptional: false, bonusScore: 3000 },
      { id: 'obj_steal_core', text: 'Robar el Núcleo Cuántico del servidor central', isCompleted: false, isOptional: false, bonusScore: 5000 },
      { id: 'obj_evac', text: 'Evacuar ambos agentes en el punto de extracción', isCompleted: false, isOptional: false, bonusScore: 4000 },
      { id: 'obj_ghost', text: 'Completar la incursión sin activar la alarma general', isCompleted: false, isOptional: true, bonusScore: 8000 }
    ]
  },
  {
    id: 'mission_2',
    name: 'Búnker Criogénico (Bio-Tech)',
    code: 'OP-FROSTBITE',
    location: 'Instalación Subglaciar GeneTech Alpha',
    difficulty: 'MEDIUM',
    description: 'Laboratorio de alto secreto. Cámaras de vigilancia avanzadas, barreras de bio-contención y muestras criogénicas de valor incalculable.',
    briefing: [
      '1. Evita las cámaras de 360° utilizando humo o el pulso EMP.',
      '2. Ambos agentes deben sincronizarse en las consolas Cryo-1 y Cryo-2.',
      '3. Asegura el contenedor criogénico antes de que la temperatura suba.',
      '4. Despeja el túnel de carga para la extracción aérea.'
    ],
    targetLootValue: 450000,
    timeLimitSeconds: 150,
    qrfSpawnInterval: 12,
    mapWidth: 1800,
    mapHeight: 1100,
    spawnP1: { x: 120, y: 520 },
    spawnP2: { x: 120, y: 600 },
    walls: [
      // Outer boundaries
      { x: 0, y: 0, width: 1800, height: 20 },
      { x: 0, y: 1080, width: 1800, height: 20 },
      { x: 0, y: 0, width: 20, height: 1100 },
      { x: 1780, y: 0, width: 20, height: 1100 },

      // Decontamination Airlock
      { x: 280, y: 20, width: 20, height: 420 },
      { x: 280, y: 660, width: 20, height: 420 },

      // Lab Central Dividing Spine
      { x: 540, y: 220, width: 20, height: 660 },
      { x: 540, y: 220, width: 440, height: 20 },
      { x: 540, y: 860, width: 440, height: 20 },

      // Cryo Chamber Vault
      { x: 1120, y: 150, width: 20, height: 320 },
      { x: 1120, y: 630, width: 20, height: 320 },
      { x: 1120, y: 150, width: 420, height: 20 },
      { x: 1120, y: 930, width: 420, height: 20 },
      { x: 1520, y: 150, width: 20, height: 800 },

      // Lab desks and cryo tubes
      { x: 400, y: 340, width: 60, height: 60, isCover: true },
      { x: 400, y: 720, width: 60, height: 60, isCover: true },
      { x: 760, y: 420, width: 80, height: 40, isCover: true },
      { x: 760, y: 640, width: 80, height: 40, isCover: true },
      { x: 1300, y: 400, width: 70, height: 70, isCover: true },
      { x: 1300, y: 630, width: 70, height: 70, isCover: true }
    ],
    doors: [
      { id: 'door_airlock', x: 280, y: 440, width: 20, height: 220, isOpen: true, isLocked: false, isVertical: true },
      { id: 'door_cryo_vault', x: 1120, y: 470, width: 20, height: 160, isOpen: false, isLocked: true, lockedReason: 'BLOQUEO CRIOGÉNICO - DUAL SYNC', isVertical: true, unlockedByTerminalGroup: 'group_cryo' },
      { id: 'door_helipad', x: 1520, y: 470, width: 20, height: 160, isOpen: true, isLocked: false, isVertical: true }
    ],
    terminals: [
      {
        id: 'term_cryo_1',
        pairedTerminalId: 'term_cryo_2',
        group: 'group_cryo',
        x: 820,
        y: 120,
        radius: 42,
        isActivated: false,
        activeByPlayer: null,
        activatedTime: 0,
        syncWindowSeconds: 3.2,
        requiresKeycard: false,
        label: 'CONSOLA CRYO-01 (MÓDULO BIO)',
        isCompleted: false,
        unlocksDoorId: 'door_cryo_vault',
        progress: 0,
      },
      {
        id: 'term_cryo_2',
        pairedTerminalId: 'term_cryo_1',
        group: 'group_cryo',
        x: 820,
        y: 980,
        radius: 42,
        isActivated: false,
        activeByPlayer: null,
        activatedTime: 0,
        syncWindowSeconds: 3.2,
        requiresKeycard: false,
        label: 'CONSOLA CRYO-02 (MÓDULO VALVULAS)',
        isCompleted: false,
        unlocksDoorId: 'door_cryo_vault',
        progress: 0,
      }
    ],
    lasers: [
      { id: 'laser_cryo_1', x1: 1130, y1: 480, x2: 1130, y2: 620, isActive: true, controlledByTerminalGroup: 'group_cryo', color: '#06b6d4' },
      { id: 'laser_cryo_2', x1: 1130, y1: 520, x2: 1130, y2: 580, isActive: true, controlledByTerminalGroup: 'group_cryo', color: '#06b6d4' }
    ],
    cameras: [
      {
        id: 'cam_bio_1',
        x: 310,
        y: 60,
        angle: Math.PI / 3,
        baseAngle: Math.PI / 3,
        sweepAngle: Math.PI / 2,
        sweepSpeed: 0.9,
        viewDistance: 260,
        viewFov: 0.65,
        isHacked: false,
        hackTimer: 0,
        detectionLevel: 0,
        detectionTarget: null,
      },
      {
        id: 'cam_bio_2',
        x: 560,
        y: 250,
        angle: Math.PI / 4,
        baseAngle: Math.PI / 4,
        sweepAngle: Math.PI / 2.2,
        sweepSpeed: 0.8,
        viewDistance: 270,
        viewFov: 0.6,
        isHacked: false,
        hackTimer: 0,
        detectionLevel: 0,
        detectionTarget: null,
      },
      {
        id: 'cam_bio_3',
        x: 560,
        y: 840,
        angle: -Math.PI / 4,
        baseAngle: -Math.PI / 4,
        sweepAngle: Math.PI / 2.2,
        sweepSpeed: 0.8,
        viewDistance: 270,
        viewFov: 0.6,
        isHacked: false,
        hackTimer: 0,
        detectionLevel: 0,
        detectionTarget: null,
      }
    ],
    enemies: [
      {
        id: 'bio_guard_1',
        type: 'guard_patrol',
        x: 420,
        y: 540,
        vx: 0,
        vy: 0,
        angle: 0,
        hp: 75,
        maxHp: 75,
        state: 'patrol',
        stateTimer: 0,
        speed: 1.6,
        viewDistance: 250,
        viewAngle: Math.PI / 3,
        patrolPoints: [{ x: 420, y: 300 }, { x: 420, y: 780 }],
        currentPatrolIdx: 0,
        investigatePos: null,
        targetPlayerId: null,
        lastShotTime: 0,
        detectionLevel: 0,
        isStunned: false,
        stunTimer: 0,
        color: '#06b6d4',
        weapon: ENEMY_WEAPONS.guard_pistol,
      },
      {
        id: 'bio_guard_2',
        type: 'guard_patrol',
        x: 750,
        y: 280,
        vx: 0,
        vy: 0,
        angle: Math.PI / 2,
        hp: 75,
        maxHp: 75,
        state: 'patrol',
        stateTimer: 0,
        speed: 1.7,
        viewDistance: 250,
        viewAngle: Math.PI / 3,
        patrolPoints: [{ x: 620, y: 280 }, { x: 980, y: 280 }],
        currentPatrolIdx: 0,
        investigatePos: null,
        targetPlayerId: null,
        lastShotTime: 0,
        detectionLevel: 0,
        isStunned: false,
        stunTimer: 0,
        color: '#06b6d4',
        weapon: ENEMY_WEAPONS.guard_pistol,
      },
      {
        id: 'bio_guard_3',
        type: 'guard_patrol',
        x: 750,
        y: 800,
        vx: 0,
        vy: 0,
        angle: -Math.PI / 2,
        hp: 75,
        maxHp: 75,
        state: 'patrol',
        stateTimer: 0,
        speed: 1.7,
        viewDistance: 250,
        viewAngle: Math.PI / 3,
        patrolPoints: [{ x: 980, y: 800 }, { x: 620, y: 800 }],
        currentPatrolIdx: 0,
        investigatePos: null,
        targetPlayerId: null,
        lastShotTime: 0,
        detectionLevel: 0,
        isStunned: false,
        stunTimer: 0,
        color: '#06b6d4',
        weapon: ENEMY_WEAPONS.guard_pistol,
      },
      {
        id: 'bio_swat_1',
        type: 'swat_enforcer',
        x: 1320,
        y: 540,
        vx: 0,
        vy: 0,
        angle: Math.PI,
        hp: 140,
        maxHp: 140,
        state: 'patrol',
        stateTimer: 0,
        speed: 1.9,
        viewDistance: 270,
        viewAngle: Math.PI / 2.8,
        patrolPoints: [{ x: 1220, y: 360 }, { x: 1420, y: 720 }],
        currentPatrolIdx: 0,
        investigatePos: null,
        targetPlayerId: null,
        lastShotTime: 0,
        detectionLevel: 0,
        isStunned: false,
        stunTimer: 0,
        color: '#f97316',
        weapon: ENEMY_WEAPONS.swat_smg,
      }
    ],
    loot: [
      { id: 'loot_vial', type: 'bio_vial', name: 'VIAL CRIOGÉNICO PROTOTIPO V-9', value: 300000, x: 1420, y: 540, weight: 0.2, isCollected: false, isPrimaryObjective: true },
      { id: 'loot_gold1', type: 'gold_bar', name: 'Lingotes de Platino Enriquecido', value: 75000, x: 1220, y: 280, weight: 0.1, isCollected: false },
      { id: 'loot_gold2', type: 'gold_bar', name: 'Lingotes de Platino Enriquecido', value: 75000, x: 1220, y: 800, weight: 0.1, isCollected: false }
    ],
    extractionZone: {
      x: 1600,
      y: 440,
      width: 150,
      height: 220,
      isActive: true,
      evacProgress: 0,
      evacRequiredSeconds: 4.0,
      name: 'HELIPUERTO DE EMERGENCIA SUR'
    },
    objectives: [
      { id: 'obj_sync_cryo', text: 'Sincronizar Consolas Cryo-01 y Cryo-02 simultáneamente', isCompleted: false, isOptional: false, bonusScore: 4000 },
      { id: 'obj_steal_vial', text: 'Extraer el Vial Criogénico Prototipo', isCompleted: false, isOptional: false, bonusScore: 6000 },
      { id: 'obj_evac_cryo', text: 'Evacuar ambos agentes en el helicóptero', isCompleted: false, isOptional: false, bonusScore: 5000 }
    ]
  },
  {
    id: 'mission_3',
    name: 'Ciudadela de Hierro (Black Site)',
    code: 'OP-IRONCLAD',
    location: 'Silo Militar Blindado Redoubt-7',
    difficulty: 'HARD',
    description: 'Instalación militar de máxima seguridad protegida por torretas automáticas, escuadrones SWAT blindados y una ojiva prototipo.',
    briefing: [
      '1. Neutraliza las torretas automáticas antes de cruzar el patio principal.',
      '2. Ambas llaves de seguridad deben insertarse en las terminales del silo al unísono.',
      '3. Asegura el Disco Prototipo Nuclear.',
      '4. Resiste la respuesta armada de la fuerza de respuesta rápida (QRF) durante la extracción.'
    ],
    targetLootValue: 750000,
    timeLimitSeconds: 180,
    qrfSpawnInterval: 9,
    mapWidth: 2000,
    mapHeight: 1200,
    spawnP1: { x: 140, y: 570 },
    spawnP2: { x: 140, y: 640 },
    walls: [
      // Perimeter
      { x: 0, y: 0, width: 2000, height: 20 },
      { x: 0, y: 1180, width: 2000, height: 20 },
      { x: 0, y: 0, width: 20, height: 1200 },
      { x: 1980, y: 0, width: 20, height: 1200 },

      // Perimeter Checkpoint
      { x: 300, y: 20, width: 20, height: 460 },
      { x: 300, y: 720, width: 20, height: 460 },

      // Quad Fortifications
      { x: 600, y: 200, width: 20, height: 350 },
      { x: 600, y: 650, width: 20, height: 350 },
      { x: 600, y: 200, width: 500, height: 20 },
      { x: 600, y: 980, width: 500, height: 20 },

      // Central Silo
      { x: 1250, y: 200, width: 20, height: 340 },
      { x: 1250, y: 660, width: 20, height: 340 },
      { x: 1250, y: 200, width: 450, height: 20 },
      { x: 1250, y: 980, width: 450, height: 20 },
      { x: 1700, y: 200, width: 20, height: 800 },

      // Tactical covers
      { x: 450, y: 400, width: 60, height: 60, isCover: true },
      { x: 450, y: 740, width: 60, height: 60, isCover: true },
      { x: 880, y: 400, width: 80, height: 50, isCover: true },
      { x: 880, y: 750, width: 80, height: 50, isCover: true },
      { x: 1450, y: 450, width: 80, height: 60, isCover: true },
      { x: 1450, y: 690, width: 80, height: 60, isCover: true }
    ],
    doors: [
      { id: 'door_silo_entry', x: 300, y: 480, width: 20, height: 240, isOpen: true, isLocked: false, isVertical: true },
      { id: 'door_silo_vault', x: 1250, y: 540, width: 20, height: 120, isOpen: false, isLocked: true, lockedReason: 'BÚNKER REFORZADO - DUAL KEYCARD', isVertical: true, unlockedByTerminalGroup: 'group_silo' },
      { id: 'door_silo_extract', x: 1700, y: 520, width: 20, height: 160, isOpen: true, isLocked: false, isVertical: true }
    ],
    terminals: [
      {
        id: 'term_silo_1',
        pairedTerminalId: 'term_silo_2',
        group: 'group_silo',
        x: 950,
        y: 120,
        radius: 45,
        isActivated: false,
        activeByPlayer: null,
        activatedTime: 0,
        syncWindowSeconds: 3.0,
        requiresKeycard: false,
        label: 'LLAVE MAESTRA NORTE',
        isCompleted: false,
        unlocksDoorId: 'door_silo_vault',
        progress: 0,
      },
      {
        id: 'term_silo_2',
        pairedTerminalId: 'term_silo_1',
        group: 'group_silo',
        x: 950,
        y: 1080,
        radius: 45,
        isActivated: false,
        activeByPlayer: null,
        activatedTime: 0,
        syncWindowSeconds: 3.0,
        requiresKeycard: false,
        label: 'LLAVE MAESTRA SUR',
        isCompleted: false,
        unlocksDoorId: 'door_silo_vault',
        progress: 0,
      }
    ],
    lasers: [
      { id: 'laser_silo_1', x1: 1260, y1: 550, x2: 1260, y2: 650, isActive: true, controlledByTerminalGroup: 'group_silo', color: '#ef4444' }
    ],
    cameras: [
      {
        id: 'cam_silo_1',
        x: 620,
        y: 230,
        angle: Math.PI / 4,
        baseAngle: Math.PI / 4,
        sweepAngle: Math.PI / 2,
        sweepSpeed: 1.1,
        viewDistance: 290,
        viewFov: 0.7,
        isHacked: false,
        hackTimer: 0,
        detectionLevel: 0,
        detectionTarget: null,
      },
      {
        id: 'cam_silo_2',
        x: 620,
        y: 950,
        angle: -Math.PI / 4,
        baseAngle: -Math.PI / 4,
        sweepAngle: Math.PI / 2,
        sweepSpeed: 1.1,
        viewDistance: 290,
        viewFov: 0.7,
        isHacked: false,
        hackTimer: 0,
        detectionLevel: 0,
        detectionTarget: null,
      }
    ],
    enemies: [
      {
        id: 'silo_guard_1',
        type: 'guard_elite',
        x: 480,
        y: 600,
        vx: 0,
        vy: 0,
        angle: 0,
        hp: 90,
        maxHp: 90,
        state: 'patrol',
        stateTimer: 0,
        speed: 1.8,
        viewDistance: 270,
        viewAngle: Math.PI / 3,
        patrolPoints: [{ x: 480, y: 350 }, { x: 480, y: 850 }],
        currentPatrolIdx: 0,
        investigatePos: null,
        targetPlayerId: null,
        lastShotTime: 0,
        detectionLevel: 0,
        isStunned: false,
        stunTimer: 0,
        color: '#ea580c',
        weapon: ENEMY_WEAPONS.swat_smg,
      },
      {
        id: 'silo_swat_1',
        type: 'swat_enforcer',
        x: 880,
        y: 320,
        vx: 0,
        vy: 0,
        angle: Math.PI / 2,
        hp: 150,
        maxHp: 150,
        state: 'patrol',
        stateTimer: 0,
        speed: 1.8,
        viewDistance: 280,
        viewAngle: Math.PI / 2.8,
        patrolPoints: [{ x: 700, y: 320 }, { x: 1100, y: 320 }],
        currentPatrolIdx: 0,
        investigatePos: null,
        targetPlayerId: null,
        lastShotTime: 0,
        detectionLevel: 0,
        isStunned: false,
        stunTimer: 0,
        color: '#dc2626',
        weapon: ENEMY_WEAPONS.swat_smg,
      },
      {
        id: 'silo_swat_2',
        type: 'swat_enforcer',
        x: 880,
        y: 880,
        vx: 0,
        vy: 0,
        angle: -Math.PI / 2,
        hp: 150,
        maxHp: 150,
        state: 'patrol',
        stateTimer: 0,
        speed: 1.8,
        viewDistance: 280,
        viewAngle: Math.PI / 2.8,
        patrolPoints: [{ x: 1100, y: 880 }, { x: 700, y: 880 }],
        currentPatrolIdx: 0,
        investigatePos: null,
        targetPlayerId: null,
        lastShotTime: 0,
        detectionLevel: 0,
        isStunned: false,
        stunTimer: 0,
        color: '#dc2626',
        weapon: ENEMY_WEAPONS.swat_smg,
      },
      {
        id: 'silo_heavy',
        type: 'heavy_boss',
        x: 1500,
        y: 600,
        vx: 0,
        vy: 0,
        angle: Math.PI,
        hp: 350,
        maxHp: 350,
        state: 'patrol',
        stateTimer: 0,
        speed: 1.5,
        viewDistance: 300,
        viewAngle: Math.PI / 2.5,
        patrolPoints: [{ x: 1500, y: 400 }, { x: 1500, y: 800 }],
        currentPatrolIdx: 0,
        investigatePos: null,
        targetPlayerId: null,
        lastShotTime: 0,
        detectionLevel: 0,
        isStunned: false,
        stunTimer: 0,
        color: '#b91c1c',
        weapon: ENEMY_WEAPONS.turret_cannon,
      }
    ],
    loot: [
      { id: 'loot_nuke_disk', type: 'prototype_disk', name: 'DISCO CUÁNTICO DE DEFENSA', value: 500000, x: 1580, y: 600, weight: 0.25, isCollected: false, isPrimaryObjective: true },
      { id: 'loot_gold_silo1', type: 'gold_bar', name: 'Lingotes de Oro Puro', value: 125000, x: 1380, y: 320, weight: 0.12, isCollected: false },
      { id: 'loot_gold_silo2', type: 'gold_bar', name: 'Lingotes de Oro Puro', value: 125000, x: 1380, y: 880, weight: 0.12, isCollected: false }
    ],
    extractionZone: {
      x: 1780,
      y: 480,
      width: 170,
      height: 240,
      isActive: true,
      evacProgress: 0,
      evacRequiredSeconds: 4.5,
      name: 'TRANSPORTE BLINDADO TITAN-4'
    },
    objectives: [
      { id: 'obj_sync_silo', text: 'Sincronizar Llaves Maestras Norte y Sur simultáneamente', isCompleted: false, isOptional: false, bonusScore: 5000 },
      { id: 'obj_steal_proto', text: 'Robar el Disco Cuántico de Defensa', isCompleted: false, isOptional: false, bonusScore: 8000 },
      { id: 'obj_evac_silo', text: 'Evacuar la unidad táctica con vida', isCompleted: false, isOptional: false, bonusScore: 6000 }
    ]
  }
];
