import { CarSpec } from '../types/game';

export const RALLY_CARS: CarSpec[] = [
  {
    id: 'quattro_s1',
    name: 'Nordic Quattro S1',
    class: 'Group B / AWD Legend',
    drivetrain: 'AWD',
    horsePower: 510,
    weightKg: 1090,
    topSpeedKmh: 228,
    acceleration: 98,
    handling: 85,
    gripFactor: 1.18,
    driftMultiplier: 1.25,
    handbrakePower: 1.35,
    suspensionStiffness: 1.15,
    engineSoundProfile: 'inline5_turbo',
    color: '#f8fafc',
    accentColor: '#f59e0b',
    stripeColor: '#0f172a',
    dimensions: {
      length: 4.24,
      width: 1.86,
      wheelbase: 2.22,
      trackWidth: 1.54,
    },
    description: 'Iconic 5-cylinder turbo monster with aggressive aerodynamics and permanent Quattro AWD. Tremendous straight-line punch and controllable power slides.',
    difficulty: 'Intermediate',
  },
  {
    id: 'stratos_rs',
    name: 'Apex Stratos HF',
    class: 'Group 4 / RWD Classic',
    drivetrain: 'RWD',
    horsePower: 320,
    weightKg: 890,
    topSpeedKmh: 215,
    acceleration: 88,
    handling: 94,
    gripFactor: 0.96,
    driftMultiplier: 1.65,
    handbrakePower: 1.6,
    suspensionStiffness: 1.25,
    engineSoundProfile: 'v6_turbo',
    color: '#059669',
    accentColor: '#fbbf24',
    stripeColor: '#ffffff',
    dimensions: {
      length: 3.71,
      width: 1.75,
      wheelbase: 2.18,
      trackWidth: 1.48,
    },
    description: 'Ultra-short wheelbase mid-engine wedge. Razor-sharp turn-in and high oversteer agility. Master the Scandinavian flick to set record times.',
    difficulty: 'Master',
  },
  {
    id: 'boxer_wrx',
    name: 'Subaru Boxer WRX',
    class: 'Rally1 / Modern WRC',
    drivetrain: 'AWD',
    horsePower: 380,
    weightKg: 1190,
    topSpeedKmh: 210,
    acceleration: 92,
    handling: 96,
    gripFactor: 1.28,
    driftMultiplier: 1.12,
    handbrakePower: 1.45,
    suspensionStiffness: 1.05,
    engineSoundProfile: 'flat4_boxer',
    color: '#1d4ed8',
    accentColor: '#fbbf24',
    stripeColor: '#fbbf24',
    dimensions: {
      length: 4.38,
      width: 1.82,
      wheelbase: 2.53,
      trackWidth: 1.55,
    },
    description: 'Modern symmetrical AWD with turbocharged boxer engine and anti-lag. Unrivaled balance, neutral handling and immense grip in all weather conditions.',
    difficulty: 'Novice',
  },
  {
    id: 'cooper_sprint',
    name: 'Mini Cooper Sprint',
    class: 'Historic / FWD Feather',
    drivetrain: 'FWD',
    horsePower: 195,
    weightKg: 720,
    topSpeedKmh: 185,
    acceleration: 75,
    handling: 98,
    gripFactor: 1.08,
    driftMultiplier: 0.95,
    handbrakePower: 1.75,
    suspensionStiffness: 1.3,
    engineSoundProfile: 'inline4_revvy',
    color: '#dc2626',
    accentColor: '#ffffff',
    stripeColor: '#ffffff',
    dimensions: {
      length: 3.05,
      width: 1.44,
      wheelbase: 2.03,
      trackWidth: 1.25,
    },
    description: 'Lightweight go-kart responsiveness. Pull the handbrake hard to swing the rear end around tight hairpins then pin the throttle to pull through.',
    difficulty: 'Intermediate',
  },
];

export function getCarById(id: string): CarSpec {
  return RALLY_CARS.find((c) => c.id === id) || RALLY_CARS[0];
}
